// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/gpfs/mnt/gpfs01/star/pwg/svomich/JetsTrees/analysis/unfolding/unfold.cxx";

#endif
